# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [21]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [22]:
# Identificar funcionários com salários acima da média
acima_media = np.where(salarios > media_salarial)
print(f"Salarios acima da media sáo {acima_media}")


Salarios acima da media sáo (array([2, 4, 5, 6]),)


In [23]:
print(f"Salarios acima da media {salarios[acima_media]}")

# outra forma de mostrar salarios acima da media
print(f"Salarios acima da media {salarios[salarios > media_salarial]}")

# outras opçoes de operar o array
print(f"Salarios abaixo da media {salarios[salarios < media_salarial]}")

print(f"Salarios abaixo de 4 mil {salarios[salarios <= 4000]}")

Salarios acima da media [4000 4500 4000 5000]
Salarios acima da media [4000 4500 4000 5000]
Salarios abaixo da media [3000 3500 2000]
Salarios abaixo de 4 mil [3000 3500 4000 2000 4000]


In [25]:
# incremento do np.where()
print(np.where(salarios > media_salarial, "acima da media", "abaixo da media"))

['abaixo da media' 'abaixo da media' 'acima da media' 'abaixo da media'
 'acima da media' 'acima da media' 'acima da media']


In [30]:
# dar bônus de 10% para os funcionários com salários abaixo da média
salario_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)
print(f"Salarios {salarios}")
print(f"Salarios com aumento de 10% {salario_bonus}")

Salarios [3000 3500 4000 2000 4500 4000 5000]
Salarios com aumento de 10% [3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [ ]:
# filtrar os salários entre 3000 e 4500 com where
# operador &
print(salarios)
print(np.where((salarios >= 3000) & (salarios <= 4500)))

[3000 3500 4000 2000 4500 4000 5000]
(array([0, 1, 2, 4, 5]),)


In [38]:
# ajustes de salarios
salarios_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
print(f"Salarios ajustados {salarios_ajustados} " )

Salarios ajustados [3150. 3675. 4200. 2000. 4725. 4200. 5000.] 


In [44]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
salarios_segundo_ajuste = np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500), salarios_ajustados * 1.1, salarios_ajustados)
print(salarios_segundo_ajuste)
print(salarios_ajustados)


[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]
[3150. 3675. 4200. 2000. 4725. 4200. 5000.]
