## Exercício

Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: `tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])`. 

Considerando uma distribuição normal:

![normal](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Standard_deviation_diagram_micro.svg/640px-Standard_deviation_diagram_micro.svg.png)

In [2]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo)
desvio_padrao = np.std(tempos_ciclo)
anomalias = np.where((tempos_ciclo > media + 2 * desvio_padrao) | (tempos_ciclo < media - 2 * desvio_padrao))
print(f"Os tempos de ciclo que estão dois desvios padrão acima ou abaixo da média são: {tempos_ciclo[anomalias]}")


Os tempos de ciclo que estão dois desvios padrão acima ou abaixo da média são: [7.2]


### Bônus

In [3]:
condicao = ((tempos_ciclo > media + 2 * desvio_padrao) | (tempos_ciclo < media - 2 * desvio_padrao))
print(condicao)

[False False False False False False False  True False]


In [4]:
print(np.where(condicao))

(array([7]),)


In [12]:
contrario_condicao = ((tempos_ciclo <= media + 2 * desvio_padrao) & (tempos_ciclo >= media - 2 * desvio_padrao))
print(np.where(contrario_condicao))

(array([0, 1, 2, 3, 4, 5, 6, 8]),)


In [13]:
print(np.where(~condicao))
print(~condicao)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)
[ True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

### Bônus 2

In [ ]:
rng = np.random.default_rng(seed=0)
tempos_gerados = rng.normal(loc=media, scale=desvio_padrao, size=100)
print(tempos_gerados)

In [15]:
print(media)
print(tempos_gerados.mean())

5.8
5.848053545223129


In [9]:
print(desvio_padrao)
print(tempos_gerados.std())

0.592546294487706
0.5701068395534514


In [10]:
condicao = ((tempos_gerados > tempos_gerados.mean() + 2 * tempos_gerados.std()) | (tempos_gerados < tempos_gerados.mean() - 2 * tempos_gerados.std()))
print(np.where(condicao))
print(tempos_gerados[condicao])

(array([12, 69]),)
[4.42231163 4.49431839]
